cmake_minimum_required(VERSION 3.31.3)
set(CMAKE_EXPORT_COMPILE_COMMANDS on)
set(CMAKE_CXX_EXTENSIONS off)
if(lucy_mac)
    set(CMAKE_OSX_ARCHITECTURES arm64)
endif()
project(Lucy)
message(STATUS "Building on ${CMAKE_BUILD_TYPE} mode...")
if(lucy_mac)
    message(STATUS "Building for macOS...")
    get_filename_component(AbsolutePath "Resources/Mac" ABSOLUTE)
    file(GLOB_RECURSE MetalShaders "Shader/**.metal")
    file(GLOB_RECURSE ResourceFiles "Resources/Mac/*")
    foreach(ResourceFile ${ResourceFiles})
        file(RELATIVE_PATH ResourcePath "${AbsolutePath}" "${ResourceFile}")
        get_filename_component(NewResourcePath "${ResourcePath}" DIRECTORY)
        set_property(SOURCE "${ResourceFile}" PROPERTY MACOSX_PACKAGE_LOCATION "Resources/${NewResourcePath}")
        source_group("Resources/${NewResourcePath}" FILES "${ResourceFile}")
    endforeach(ResourceFile)
    add_executable(Lucy MACOSX_BUNDLE ${ResourceFiles} ${MetalShaders})
    if(NOT lucy_clangd)
        file(GLOB_RECURSE ObjCppSources "Source/**.mm")
    endif()
    #Remove Source/Lucy.cpp and other .cpp files
    target_sources(Lucy PRIVATE ${ObjCppSources})
    set_source_files_properties(${MetalShaders} PROPERTIES LANGUAGE METAL COMPILE_OPTIONS -std=metal3.2)
    if(lucy_codesign)
        if(lucy_teamid)
            set_target_properties(Lucy PROPERTIES MACOSX_BUNDLE_INFO_PLIST Info.plist XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER com.arasaka.lucy XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "${lucy_teamid}" XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "${lucy_codesign}")
        else()
            set_target_properties(Lucy PROPERTIES MACOSX_BUNDLE_INFO_PLIST Info.plist XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER com.arasaka.lucy XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "${lucy_codesign}")
        endif()
    elseif(lucy_teamid)
        set_target_properties(Lucy PROPERTIES MACOSX_BUNDLE_INFO_PLIST Info.plist XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER com.arasaka.lucy XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "${lucy_teamid}")
    else()
        set_target_properties(Lucy PROPERTIES MACOSX_BUNDLE_INFO_PLIST Info.plist XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER com.arasaka.lucy)
    endif()
    find_library(foundation Foundation)
    if(NOT foundation)
        message(FATAL_ERROR "Foundation not found")
    endif()
    find_library(quartzcore QuartzCore)
    if(NOT quartzcore)
        message(FATAL_ERROR "QuartzCore not found")
    endif()
    find_library(metal Metal)
    if(NOT metal)
        message(FATAL_ERROR "Metal not found")
    endif()
    find_library(iokit IOKit)
    if(NOT iokit)
        message(FATAL_ERROR "IOKit not found")
    endif()
    find_library(appkit AppKit)
    if(NOT appkit)
        message(FATAL_ERROR "AppKit not found")
    endif()
    target_link_libraries(Lucy PRIVATE ${foundation} ${quartzcore} ${metal} ${iokit} ${appkit})
    target_compile_definitions(Lucy PRIVATE lucy_mac=)
endif()
target_compile_definitions(Lucy PRIVATE lucy_major=0 lucy_middle=0 lucy_minor=1 lucy_game=${lucy_game} lucy_title="${lucy_game}")
if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    target_compile_definitions(Lucy PRIVATE lucy_debug=)
    target_compile_options(Lucy PRIVATE -Werror -Wall -Wextra -Wpedantic -fno-rtti -fno-exceptions -g)
    target_link_options(Lucy PRIVATE -g)
else()
    target_compile_options(Lucy PRIVATE -Werror -Wall -Wextra -Wpedantic -O3 -fno-rtti -fno-exceptions -flto)
    target_link_options(Lucy PRIVATE -flto)
endif()
target_include_directories(Lucy PRIVATE Source)
target_compile_features(Lucy PRIVATE cxx_std_23)
file(GLOB_RECURSE CppSources "Source/**.cpp")
file(GLOB_RECURSE CppEditors "Editor/**.cpp")
target_sources(Lucy PRIVATE ${CppSources} ${CppEditors})